### ISSUE TITLE
More currency and region support 

### ISSUE THREAD

**Issue by Zaxx69** [psuzn/Play-Deals#60]
It would really help if there is more currency support and region as some apps are banned in some region

**Comment by psuzn** [comment]
Don't think we can support multiple regions-specific apps without significant work on the [backend](https://github.com/psuzn/play-deals-backend) side but can definitely support multiple currencies.

**Comment by Zaxx69** [comment]
Ok bro

**Comment by psuzn** [comment]
With the release [v2.2.0](https://github.com/psuzn/Play-Deals/releases/tag/v2.2.0) this has been addressed
