### ISSUE TITLE
Notification bug 

### ISSUE THREAD

**Issue by Zaxx69** [psuzn/Play-Deals#72]
![Screenshot_2024-01-13-21-50-02-88_3822ac0e29cfec8970059bb21d01f05e.jpg](https://github.com/psuzn/Play-Deals/assets/138523882/59435f46-3bef-4a0c-9ed2-38e29125937b)

**Comment by Zaxx69** [comment]
It should show the new price instead of same price

**Comment by psuzn** [comment]
Good catch, thank you.

This is an issue with the backend and I am closing this in favour of https://github.com/psuzn/Play-Deals-Backend/issues/51
