### ISSUE TITLE
Add F-droid and Github badges to Readme

### ISSUE THREAD

**Issue by inson1** [psuzn/Play-Deals#77]
I think get it on gihub badge looks better than download android apk

**Comment by psuzn** [comment]
It took too long to list it on F-droid and surely will add a badge. Would appreciate a PR if you want to add it. You can just copy and paste it from [here](https://gitlab.com/fdroid/artwork/-/blob/master/badge/README.md).

**Comment by psuzn** [comment]
Again, thanks for the feedback.
