### ISSUE TITLE
Offers are not real

### ISSUE THREAD

**Issue by Erz3** [psuzn/Play-Deals#83]
It was working fine one month ago. Actually, when I tap on a deal, It opening Google Play with the original price.

**Comment by psuzn** [comment]
They are real but they expire with time. The [backend](https://github.com/psuzn/Play-Deals-Backend) should automatically remove expired items but there is a known issue with it that sometimes it misses and never removes it. I've not gotten to debug and fix it. 

About the deals, they will be replenished within 24 hours.

**Comment by psuzn** [comment]
I am closing this for now! 

Thanks @Erz3
