### ISSUE TITLE
Feature request: exclude filter

### ISSUE THREAD

**Issue by c-key** [psuzn/Play-Deals#84]
It would be nice to have an exclude filter, so the scrolling list is smaller and I didn't see entries that are not interesst, like icon packs or watch faces.

**Comment by psuzn** [comment]
Currently, there is little info on the [existing model](https://github.com/psuzn/Play-Deals-Backend/blob/443d551b0866a35141fc812c93661b611d288910/backend/src/main/resources/db/migration/V20230705134752__init.sql#L1) to identify apps such as games, icon packs, or watch faces.
