### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by LucianoVg** [psuzn/Play-Deals#89]
![Screenshot_20241201_130129_Play Deals](https://github.com/user-attachments/assets/b4c4e87d-3703-4aae-943e-644f6b766766)

App version: V2.2.1-33

**Comment by psuzn** [comment]
It was an issue with the provider and should be fixed now. 

I will close this once you verify it

**Comment by LucianoVg** [comment]
Perfect, it works now!!
Thank you very much!
